### ISSUE TITLE
Ligature for -> is broken

### ISSUE THREAD

**Issue by prokopiy** [jonathanmarvens/atom-language-erlang#14]
A similar problem is described in
https://github.com/atom/atom/issues/9372#issuecomment-152851269

Please correct it.

**Comment by janl** [comment]
You mean that `->` is rendered as a single arrow char? I’d be willing to accept a PR, but closing this.

**Comment by ConsoleTVs** [comment]
This should be fixed. it's annoying that ligatures like this does not work in erlang, specialy when -> is used a lot.

**Comment by ConsoleTVs** [comment]
Basicaly; - and > are tokenized as separate tokens. This should be fixed, might you take a look at it please?

**Comment by attah** [comment]
How is this closed when the PR is still open?
