### ISSUE TITLE
Willing to take over maintainership

### ISSUE THREAD

**Issue by janl** [jonathanmarvens/atom-language-erlang#22]
Heya @jonathanmarvens, I’d be happy to take over maintaining this. My fork already includes all outstanding PRs merged, but I’d need to be able to publish this to `apm`, and I think that’s something that you’d need to add me to.

If you don’t feel like doing this, or don’t have the tie I’m happy to maintain my fork under a different name (say `atom-language-erlang2` or something, to make clear to people what’s what).

Not trying a hostile take over, just trying to make my fellow Erlanger’s lives a little easier :)

Thanks for all the hard work here!

**Comment by carlisom** [comment]
If you decide to maintain this repo under a different name please update this issue with the information  so people can find it.

**Comment by janl** [comment]
I will!

**Comment by jonathanmarvens** [comment]
@janl Thank you. I've added you as a collaborator on this repository, so you should be able to push to this repository and then publish new versions of the package. LMK if that works for you.

**Comment by janl** [comment]
Thanks, I’ve merged everything and published to apm. I messed up the versions a little bit (commit says 3.0.1 where I meant 3.1.0 and `app publish` then bumped again to 3.2.0, but no biggie I believe.
